packages:
  - playground

catalog:
  '@antfu/ni': ^25.0.0
  '@feathersjs/adapter-commons': ^5.0.34
  '@feathersjs/authentication': ^5.0.34
  '@feathersjs/authentication-client': ^5.0.34
  '@feathersjs/authentication-local': ^5.0.34
  '@feathersjs/configuration': ^5.0.34
  '@feathersjs/feathers': ^5.0.34
  '@feathersjs/generators': ^5.0.34
  '@feathersjs/memory': ^5.0.34
  '@feathersjs/mongodb': ^5.0.34
  '@feathersjs/rest-client': ^5.0.34
  '@feathersjs/socketio-client': ^5.0.34
  '@feathersjs/typebox': ^5.0.34
  '@gabortorma/feathers-nitro-adapter': ^0.6.0
  '@gabortorma/feathers-pinia': ^5.0.1
  '@gabortorma/mwm': ^0.9.3
  '@gabortorma/nuxt-eslint-layer': ^1.0.0
  '@nuxt/devtools': ^2.6.2
  '@nuxt/kit': ^4.0.1
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^4.0.1
  '@nuxt/test-utils': ^3.19.2
  '@pinia/nuxt': ^0.11.2
  '@playwright/test': ^1.54.1
  '@types/node': ^24.1.0
  change-case: ^5.4.4
  consola: ^3.4.2
  defu: ^6.1.4
  dotenv-cli: ^9.0.0
  nuxt: ^4.0.1
  nuxt-mcp: ^0.2.3
  ofetch: ^1.4.1
  pinia: ^3.0.3
  release-it: ^19.0.4
  socket.io-client: ^4.8.1
  typescript: ^5.8.3
  vitest: ^3.2.4
  vitest-mongodb: ^1.0.1
  vue: ^3.5.18
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - mongodb-memory-server
  - unrs-resolver
  - vue-demi
